export const pages=[['overview','Overview','Business performance at a glance'],['trends','Sales trends','Revenue, volume and changes over time'],['products','Product intelligence','Understand the shape of your portfolio'],['customers','Customer intelligence','Your customers, their contribution and buying patterns'],['geography','Geography','Performance across your sales organization'],['commercial','Commercial','Pricing realization and discount exposure'],['supply-chain','Supply chain','Manufacturing, logistics and delivery timelines'],['pharma-risk','Pharma risk','Shelf life and storage conditions at the time of sale'],['tax','Tax & terms','GST components and commercial terms'],['explorer','Transaction explorer','Trace every number back to its source']];
export type Filters=Record<string,string[]>;
export type Row=Record<string,any>;
export const labels:Record<string,string>={net:'Net sales',gross:'Gross sales',discount:'Discount cost',quantity:'Quantity sold',invoices:'Invoices',discount_pct:'Weighted discount',customers:'Active customers',brands:'Brands',materials:'Materials',avg_invoice:'Average invoice value',tax:'Total GST',realized_price:'Realized price',therapies:'Therapies',therapy:'Therapy',brand:'Brand',division:'Division',customer_name:'Customer',customer:'Customer ID',plant_name:'Plant location',plant:'Plant',district:'Sales district',city:'City',office:'Sales office',group:'Sales group',ship_city:'Ship-to city',classification:'Classification',portfolio:'Main / specialty',product:'Product',material:'Material',mother_brand:'Mother brand',therapy1:'Therapy subgroup',material_group:'Product group',storage:'Storage condition',manufacturing:'Manufacturing model',transporter:'Transporter',payment:'Payment term',customer_group:'Customer group',fiscal_year:'Fiscal year',year:'Calendar year',month:'Month',date:'Invoice date',invoice:'Invoice number',batch:'Batch',mfg_date:'Manufactured',expiry_date:'Expiry date',shelf_days:'Shelf life (days)',rate_before:'Rate before discount',rate_after:'Rate after discount',mrp:'MRP',cgst:'CGST',sgst:'SGST',igst:'IGST',utgst:'UTGST'};
export const monetary=new Set(['net','gross','discount','avg_invoice','tax','realized_price','near_expiry','cold_revenue','mrp','rate_before','rate_after','cgst','sgst','igst','utgst']);
Object.assign(labels,{average_shelf:'Average shelf life (days)',median_shelf:'Median shelf life (days)',cold_revenue:'Cold chain revenue',cold_pct:'Cold chain share',near_expiry:'Near-expiry revenue',near_quantity:'Near-expiry quantity',shipments:'Shipments',rolling:'Rolling net sales'});
Object.assign(labels,{_source_file:'Source file',_source_sheet:'Source sheet',_source_row:'Source row'});
export function fmt(n:any,key='net',full=false):string {if(n==null||!Number.isFinite(Number(n)))return 'Unavailable';const v=Number(n);if(key.endsWith('pct')||['mom','yoy'].includes(key))return v.toFixed(2)+'%';if(monetary.has(key)){const a=Math.abs(v);if(!full&&a>=1e7)return '₹'+(v/1e7).toFixed(2)+' Cr';if(!full&&a>=1e5)return '₹'+(v/1e5).toFixed(2)+' L';return '₹'+v.toLocaleString('en-IN',{maximumFractionDigits:full?2:0});}return v.toLocaleString('en-IN',{maximumFractionDigits:2});}
export async function api(path:string,body?:unknown,method?:string,signal?:AbortSignal){const res=await fetch(path,{signal,method:method||(body?'POST':'GET'),headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});if(!res.ok){const e=await res.json().catch(()=>({detail:'Could not connect. Check that the application is running.'}));throw new Error(typeof e.detail==='string'?e.detail:'Please check the request values.');}return res.json();}
