'use client';
import {useEffect,useRef} from 'react';
import * as echarts from 'echarts';
import {fmt,Row} from '../lib';
type Props={title:string;subtitle?:string;rows:Row[];kind?:string;metric?:string;second?:string;onSelect?:(name:string)=>void;};
export default function Chart({title,subtitle,rows,kind='bar',metric='net',second,onSelect}:Props){const root=useRef<HTMLDivElement>(null);const valid=rows.filter(r=>r.name!=null&&r[metric]!=null);useEffect(()=>{if(!root.current||!valid.length)return;const chart=echarts.init(root.current,undefined,{renderer:'canvas'});const horizontal=kind==='bar';const data=horizontal?[...valid].slice(0,10).reverse():valid;const names=data.map(r=>String(r.name));let option:any={animation:false,color:['#e47128','#a7adb5','#e5b553','#b8625e'],aria:{enabled:true,description:title},textStyle:{fontFamily:'Inter, sans-serif',fontSize:12,color:'#69727f'},tooltip:{trigger:'axis',renderMode:'richText',formatter:(p:any)=>{const r=data[(Array.isArray(p)?p[0]:p).dataIndex];if(!r)return '';return [r.name,...[metric,'gross','quantity','invoices','discount_pct','mom','yoy'].filter((v,i,a)=>a.indexOf(v)===i&&r[v]!=null).map(k=>k.replaceAll('_',' ')+': '+fmt(r[k],k,true))].join('\n');}},grid:{top:24,bottom:36,left:horizontal?155:62,right:second?60:25,containLabel:false},xAxis:{type:horizontal?'value':'category',data:horizontal?undefined:names,axisLine:{show:false},axisTick:{show:false},splitLine:{show:horizontal,lineStyle:{color:'#edf0f2'}},axisLabel:{formatter:horizontal?(v:number)=>fmt(v,metric):undefined,hideOverlap:true}},yAxis:{type:horizontal?'category':'value',data:horizontal?names:undefined,axisLine:{show:false},axisTick:{show:false},splitLine:{show:!horizontal,lineStyle:{color:'#edf0f2'}},axisLabel:{width:140,overflow:'truncate',formatter:horizontal?undefined:(v:number)=>fmt(v,metric)}},series:[{type:['line','area','combo'].includes(kind)?'line':'bar',data:data.map(r=>r[metric]),smooth:.25,symbolSize:5,barMaxWidth:26,itemStyle:{borderRadius:horizontal?[0,3,3,0]:[3,3,0,0]},areaStyle:kind==='area'?{color:'#e47128',opacity:.08}:undefined}]};
if(kind==='combo'||kind==='pareto'){option.yAxis=[option.yAxis,{type:'value',splitLine:{show:false},axisLabel:{formatter:(v:number)=>fmt(v,second||'discount_pct')}}];let cumulative=0;const total=data.reduce((s,r)=>s+(r[metric]||0),0);option.series=[{type:'bar',data:data.map(r=>r[metric]),barMaxWidth:30},{type:'line',yAxisIndex:1,smooth:.2,data:data.map(r=>kind==='pareto'?(cumulative+=r[metric])/total*100:r[second||'quantity'])}];}
if(kind==='dual'){option.series=[{name:'Base year',type:'line',data:data.map(r=>r[metric]),smooth:.2},{name:'Comparison year',type:'line',data:data.map(r=>r[second||'previous']),smooth:.2}];option.legend={bottom:0};}
if(kind==='stacked'||kind==='percent'){const keys=(second||'').split(',');option.legend={bottom:0,type:'scroll'};option.grid.bottom=55;option.series=keys.map((key,i)=>({name:key,type:'bar',stack:'total',barMaxWidth:35,itemStyle:{color:['#df7b34','#b0b7bf','#e9b85b','#956d4b'][i%4]},data:data.map(r=>kind==='percent'?100*(r[key]||0)/(r[metric]||1):r[key])}));if(kind==='percent')option.yAxis={...option.yAxis,max:100,axisLabel:{formatter:'{value}%'}};option.tooltip.formatter=undefined;}
if(kind==='heatmap'){const xs=[...new Set(data.map(r=>r.name))],ys=[...new Set(data.map(r=>r.category))];option={...option,grid:{top:10,bottom:85,left:150,right:20},xAxis:{type:'category',data:xs,axisLabel:{width:70,overflow:'truncate',rotate:25}},yAxis:{type:'category',data:ys,axisLabel:{width:130,overflow:'truncate'}},visualMap:{min:0,max:Math.max(...data.map(r=>r[metric])),orient:'horizontal',left:'center',bottom:0,inRange:{color:['#fff3e8','#cb651e']}},series:[{type:'heatmap',data:data.map(r=>[xs.indexOf(r.name),ys.indexOf(r.category),r[metric]])}],tooltip:{trigger:'item',renderMode:'richText',formatter:(p:any)=>{const r=data[p.dataIndex];return r.name+' / '+r.category+'\n'+fmt(r[metric],metric)}}};}
if(kind==='treemap'){option={...option,xAxis:undefined,yAxis:undefined,series:[{type:'treemap',roam:false,breadcrumb:{show:false},label:{show:true,formatter:'{b}',color:'#fff'},data:data.map(r=>({name:r.name,value:r[metric]})),colorMappingBy:'value',levels:[{itemStyle:{borderColor:'#fff',borderWidth:3,gapWidth:3},color:['#a9551e','#c66624','#df853f','#a17a54']}]}]};}
if(kind==='scatter'){option.xAxis={...option.xAxis,type:'value',data:undefined,name:second||'quantity',nameLocation:'middle',nameGap:26};option.series=[{type:'scatter',data:data.map(r=>[r[second||'quantity'],r[metric]]),symbolSize:(v:any,p:any)=>Math.min(40,8+Math.sqrt(Math.abs(data[p.dataIndex].invoices||1))/2),itemStyle:{opacity:.65}}];option.tooltip.trigger='item';}
if(kind==='waterfall'){option.series=[{type:'bar',stack:'total',itemStyle:{color:'transparent'},data:[0,data[2]?.[metric],0],silent:true},{type:'bar',stack:'total',barMaxWidth:70,data:data.map((r,i)=>({value:r[metric],itemStyle:{color:i===1?'#b8625e':i===2?'#e47128':'#a7adb5'}}))}];}
chart.setOption(option);chart.on('click',(p:any)=>{const name=data[p.dataIndex]?.name;if(name!=null)onSelect?.(String(name));});const resize=new ResizeObserver(()=>chart.resize());resize.observe(root.current);return()=>{resize.disconnect();chart.dispose();};},[rows,kind,metric,second,onSelect]);return <section className="chart-panel"><header><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</header>{valid.length?<><div ref={root} className="chart" role="img" aria-label={title}/>{onSelect&&<details className="chart-selection"><summary>Select a category</summary><div>{valid.slice(0,30).map(r=><button key={r.name} onClick={()=>onSelect(String(r.name))}>{r.name}</button>)}</div></details>}</>:<div className="chart-empty">Required data is unavailable in this selection.</div>}</section>}
