'use client';
import Chart from './Chart';
import {Row,labels,fmt,Filters} from '../lib';
export function Metrics({values,keys=['net','gross','discount','quantity','invoices','discount_pct']}:{values:Row;keys?:string[]}){return <div className="metrics">{keys.map((key,i)=><div className={'metric '+(i===0?'primary':'')} key={key}><span title={{net:'Total Net Amount after discounts.',gross:'Total Sale Value before discounts.',discount:'Gross sales minus net sales.',discount_pct:'(Gross minus net) divided by gross, weighted across all rows.',tax:'Sum of all four GST components; unavailable if components are missing.'}[key]||'Calculated for the current selection.'}>{labels[key]||key.replaceAll('_',' ')}</span><strong data-testid={'kpi-'+key}>{fmt(values[key],key)}</strong></div>)}</div>}
export default function Dashboard({page,data,onFilter,metric='net'}:{page:string;data:Row;onFilter:(key:string,value:string)=>void;metric?:string}){
const {kpis:k,trend:t,groups:g,extra:e,distributions:d,durations}=data;
const bars=(key:string,title?:string,m=metric,kind='bar')=><Chart key={key+title} title={title||`${labels[key]} performance`} subtitle={`${labels[m]||m} · select to filter`} rows={g[key]||[]} metric={m} kind={kind} onSelect={value=>onFilter(key==='customer_name'?'customer_name':key,value)}/>;
const composition=(key:string,title:string)=><Chart title={title} rows={[{name:'Selected sales',net:k.net,...Object.fromEntries((g[key]||[]).filter((r:Row)=>r.name).map((r:Row)=>[r.name,r.net]))}]} kind='percent' second={(g[key]||[]).filter((r:Row)=>r.name).map((r:Row)=>r.name).join(',')}/>;
const waterfall=<Chart title="From gross to net" subtitle="Gross sales less discount cost" kind="waterfall" rows={[{name:'Gross sales',net:k.gross},{name:'Discount',net:k.discount},{name:'Net sales',net:k.net}]}/>;
return <><Metrics values={k}/><div className="support-metrics">{['customers','brands','materials','avg_invoice','tax'].map(key=><span key={key}>{labels[key]} <strong>{fmt(k[key],key)}</strong></span>)}</div><div className="insights"><span className="insight-mark">Insight</span>{data.insights.map((s:string)=><span key={s}>{s}</span>)}</div><div className="chart-grid">
{page==='overview'&&<><div className="wide"><Chart title="Monthly net sales" subtitle="Invoice month · full selected date range" rows={t} kind="area"/></div>{bars('therapy','Therapy contribution') }<Chart title="Sales and volume" subtitle="Net sales · quantity on right axis" rows={t} kind="combo" second="quantity"/>{waterfall}{bars('division','Sales by division')}{bars('brand','Leading brands')}{bars('customer_name','Leading customers')}</>}
{page==='trends'&&<><Chart title="Monthly net sales" rows={t} kind="line"/><Chart title="Month-over-month growth" subtitle="Only adjacent calendar months are compared" rows={t} metric="mom" kind="column"/><Chart title="Year-over-year growth" subtitle="Same calendar month in the previous year" rows={t} metric="yoy" kind="column"/><Chart title="Quantity trend" rows={t} metric="quantity" kind="area"/><Chart title="Invoices and average invoice value" rows={t} metric="invoices" kind="combo" second="avg_invoice"/><Chart title="Weighted discount trend" rows={t} metric="discount_pct" kind="line"/><Chart title="Rolling three-month net sales" subtitle="Requires three consecutive months" rows={t} metric="rolling" kind="line"/></>}
{page==='products'&&<>{bars('therapy','Therapy revenue ranking')}{bars('therapy','Portfolio composition','net','treemap')}{bars('brand','Leading brands')}{bars('brand','Brand Pareto','net','pareto')}{bars('classification','Revenue by classification')}<Chart title="Brand revenue and volume" subtitle="Bubble size · invoice count" rows={g.brand||[]} kind="scatter"/>{bars('product','Realized price by product','realized_price')}{composition('portfolio','Main and specialty mix')}<section className="chart-panel hierarchy"><h3>Explore the product hierarchy</h3><p>Choose a category to narrow every chart. Continue through the next level.</p>{['therapy','therapy1','material_group','classification','mother_brand','brand','product','material'].map(key=><label key={key}>{labels[key]}<select value="" onChange={ev=>ev.target.value&&onFilter(key,ev.target.value)}><option value="">Select {labels[key]?.toLowerCase()}</option>{(g[key]||[]).filter((r:Row)=>r.name).map((r:Row)=><option key={r.name}>{r.name}</option>)}</select></label>)}</section></>}
{page==='customers'&&<>{bars('customer_name','Leading customers')}{bars('customer_name','Customer Pareto','net','pareto')}<Chart title="Customer sales and discount" rows={g.customer_name||[]} metric="discount_pct" second="net" kind="scatter"/><Chart title="Purchase frequency and invoice value" rows={g.customer_name||[]} metric="avg_invoice" second="invoices" kind="scatter"/>{bars('customer_name','Customer quantity','quantity')}{bars('customer_name','Customer discount cost','discount')}{bars('customer_group','Customer groups')}{g.customer_name?.length===1&&<section className="chart-panel"><h3>{g.customer_name[0].name}</h3><Metrics values={g.customer_name[0]} keys={['net','quantity','invoices','avg_invoice','discount_pct']}/></section>}</>}
{page==='geography'&&<><div className="notice wide">Geography is shown as source-reported rankings. The workbook has no verified coordinates, so no locations are guessed.</div>{['plant_name','district','city','office','group','ship_city'].map(key=>bars(key))}</>}
{page==='commercial'&&<>{waterfall}{bars('brand','Discount cost by brand','discount','pareto')}{bars('customer_name','Discount cost by customer','discount','pareto')}<Chart title="Sales and weighted discount" rows={g.brand||[]} kind="scatter" metric="discount_pct" second="net"/><Chart title="Discount and volume" subtitle="Association only; no causal inference" rows={g.brand||[]} kind="scatter" metric="discount_pct" second="quantity"/><Chart title="Quantity-weighted price bridge" rows={[{name:'MRP',net:e.prices?.mrp},{name:'Before discount',net:e.prices?.before},{name:'After discount',net:e.prices?.after}]} kind="column"/><Chart title="Discount distribution" subtitle="5 percentage-point bands" rows={d.discount_rate||[]} metric="quantity" kind="column"/>{bars('therapy','Weighted discount by therapy','discount_pct')}{bars('plant_name','Weighted discount by plant','discount_pct')}</>}
{page==='supply-chain'&&<>{bars('manufacturing','Manufacturing model')}{composition('manufacturing','Manufacturing revenue mix')}{bars('transporter','Transporter shipments','shipments')}{bars('transporter','Transporter sales exposure')}{bars('transporter','Transporter volume','quantity')}{['po_days','delivery_days','lr_days'].map((key,i)=><Chart key={key} title={['PO to invoice','Order to delivery','Invoice to LR'][i]} subtitle={`Mean ${fmt(durations[key]?.average,'days')} · Median ${fmt(durations[key]?.median,'days')} · P90 ${fmt(durations[key]?.p90,'days')} days. ${fmt(durations[key]?.valid,'count')} valid rows.`} rows={d[key]||[]} metric="quantity" kind="column"/>)}</>}
{page==='pharma-risk'&&<><div className="wide"><Metrics values={{...e.risk,average_shelf:durations.shelf_days?.average,median_shelf:durations.shelf_days?.median}} keys={['average_shelf','median_shelf','cold_revenue','cold_pct','near_expiry','near_quantity']}/></div>{bars('storage','Revenue by storage condition')}<Chart title='Cold chain sales mix' rows={[{name:'Selected sales',net:k.net,'Cold chain':e.risk?.cold_revenue,'Other reported storage':e.risk?.cold_revenue==null?null:k.net-e.risk.cold_revenue}]} kind='percent' second='Cold chain,Other reported storage'/><Chart title="Shelf-life revenue exposure" rows={e.shelf||[]} kind="column"/><Chart title="Remaining shelf life" subtitle="At invoice date · 30-day bands; negative = expired at sale" rows={d.shelf_days||[]} metric="quantity" kind="column"/><Chart title="Manufacturing age at sale" subtitle="Valid chronological records · 30-day bands" rows={d.age_days||[]} metric="quantity" kind="column"/><Chart title="Average shelf life by brand" rows={e.brand_shelf||[]} metric="days"/>{bars('brand','Brand sales exposure')}</>}
{page==='tax'&&<><Chart title="GST composition" subtitle="Source tax components; not a legal jurisdiction assessment" rows={Object.entries(e.taxes||{}).map(([name,net])=>({name:name.toUpperCase(),net}))} kind="column"/><Chart title="Tax by invoice month" rows={(e.monthly_tax||[]).map((r:Row)=>({...r,net:['cgst','sgst','igst','utgst'].every(k=>r[k]!=null)?r.cgst+r.sgst+r.igst+r.utgst:null}))} kind="line"/>{bars('payment','Sales by payment term')}{bars('payment','Invoice value by payment term','avg_invoice')}{bars('plant_name','GST by plant','tax')}</>}
{e.matrix&&<Chart title='Revenue matrix' rows={e.matrix.map((r:Row)=>({...r,name:r.x,category:r.y}))} kind='heatmap'/>}{e.quadrants&&<section className='chart-panel wide'><h3>Commercial quadrants</h3><p>Median thresholds: {fmt(e.thresholds.sales)} net sales · {fmt(e.thresholds.discount,'discount_pct')} discount</p><div className='matrix-table'><table><thead><tr><th>Brand</th><th>Net sales</th><th>Weighted discount</th><th>Quadrant</th></tr></thead><tbody>{e.quadrants.map((r:Row)=><tr key={r.name}><td>{r.name}</td><td>{fmt(r.net)}</td><td>{fmt(r.discount_pct,'discount_pct')}</td><td>{r.quadrant}</td></tr>)}</tbody></table></div></section>}{e.expiry_matrix&&<section className='chart-panel wide'><h3>Expiry risk by brand</h3><div className='matrix-table'><table><thead><tr><th>Brand</th><th>Near-expiry revenue</th><th>Average remaining days</th></tr></thead><tbody>{e.expiry_matrix.map((r:Row)=><tr key={r.name}><td>{r.name}</td><td>{fmt(r.risk)}</td><td>{fmt(r.days,'days')}</td></tr>)}</tbody></table></div></section>}{e.plant_tax&&<Chart title='GST components by plant' rows={e.plant_tax.map((r:Row)=>({...r,net:r.cgst+r.sgst+r.igst+r.utgst}))} kind='stacked' second='cgst,sgst,igst,utgst'/>}{e.matrix&&<section className="chart-panel wide"><h3>{page==='customers'?'Customer × therapy':page==='geography'?'Plant × ship-to city':'Transporter × storage condition'}</h3><div className="matrix-table"><table><thead><tr><th>Category</th><th>Breakdown</th><th>Net sales</th></tr></thead><tbody>{e.matrix.slice(0,30).map((r:Row,i:number)=><tr key={i}><td>{r.x}</td><td>{r.y}</td><td><span className="heat-cell" style={{background:`rgba(228,113,40,${.04+.22*(r.net/(e.matrix[0]?.net||1))})`}}>{fmt(r.net)}</span></td></tr>)}</tbody></table></div></section>}
</div></>}

