'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Activity,LayoutDashboard,ChartNoAxesCombined,Pill,Users,MapPin,Receipt,Truck,ShieldCheck,Landmark,Table2,PanelLeftClose,Upload,Plus,ArrowUpRight,FileSpreadsheet,X,SlidersHorizontal,Download,Trash2,Check,ChevronRight,Database,LoaderCircle,Info} from 'lucide-react';
import Dashboard from '../components/Dashboard';
import Comparison from '../components/Comparison';
import {upload as uploadBlob} from '@vercel/blob/client';
import {api,pages,fmt,labels,Filters,Row} from '../lib';
const icons=[LayoutDashboard,ChartNoAxesCombined,Pill,Users,MapPin,Receipt,Truck,ShieldCheck,Landmark,Table2];
const primary=['fiscal_year','year','month','division','therapy','brand','plant','district','customer'];
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><header><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}><X size={18}/></button></header>{children}</dialog>}
export default function Home(){
const [sid,setSid]=useState(''),[meta,setMeta]=useState<Row|null>(null),[page,setPage]=useState('overview'),[filters,setFilters]=useState<Filters>({}),[data,setData]=useState<Row|null>(null),[quality,setQuality]=useState<Row|null>(null),[busy,setBusy]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState(''),[collapsed,setCollapsed]=useState(false),[drag,setDrag]=useState(false),[schema,setSchema]=useState<Row|null>(null),[metric,setMetric]=useState('net'),[exclude,setExclude]=useState(false),[buckets,setBuckets]=useState([180,365,548]),[search,setSearch]=useState(''),[sort,setSort]=useState('date'),[descending,setDescending]=useState(true),[tablePage,setTablePage]=useState(0),[columns,setColumns]=useState(['date','invoice','customer_name','brand','therapy','quantity','net','plant_name']),[detail,setDetail]=useState<Row|null>(null),[exportPages,setExportPages]=useState(pages.slice(0,9).map(p=>p[0])),[uploads,setUploads]=useState<Row[]>([]);
const input=useRef<HTMLInputElement>(null),generation=useRef(0),queryCache=useRef(new Map<string,Row>());
const loaded=!!meta?.rows;const current=pages.find(p=>p[0]===page)!;
const reset=()=>{generation.current++;queryCache.current.clear();setData(null);setFilters({});setMeta(null);setQuality(null);setSid('');setSearch('');setTablePage(0);setExclude(false);setPage('overview');setUploads([]);setDetail(null);setModal('');};
useEffect(()=>{
  if(!sid||!loaded||busy)return;
  const body={filters,exclude_partial:exclude,buckets,search,sort,descending,page:tablePage,size:50};
  const key=JSON.stringify([sid,page,body]),cached=queryCache.current.get(key);
  if(cached){setData(cached);setLoading(false);return;}
  const controller=new AbortController(),gen=generation.current;
  setLoading(true);setData(null);
  const timer=setTimeout(()=>api(`/api/sessions/${sid}/analytics/${page}`,body,undefined,controller.signal).then(r=>{
    if(!controller.signal.aborted&&gen===generation.current){
      if(queryCache.current.size>=40)queryCache.current.delete(queryCache.current.keys().next().value!);
      queryCache.current.set(key,r);setData(r);
    }
  }).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)}),search?250:50);
  return()=>{controller.abort();clearTimeout(timer)};
},[sid,meta,page,filters,exclude,buckets,search,sort,descending,tablePage,busy,loaded]);
const refresh=async(id:string)=>{const [m,q]=await Promise.all([api(`/api/sessions/${id}/metadata`),api(`/api/sessions/${id}/quality`)]);setMeta(m);setQuality(q)};
async function upload(files:File[],replace=false){if(!files.length||busy)return;setError('');setBusy('Uploading and auditing workbook…');generation.current++;queryCache.current.clear();setData(null);let id=sid;try{if(!id){id=(await api('/api/sessions',{})).id;setSid(id)}for(const file of files){setBusy('Reading and auditing '+file.name+'…');setUploads(u=>[...u.filter(x=>x.name!==file.name),{name:file.name,size:file.size,status:'Validating and processing'}]);try{if(location.hostname==='localhost'||location.hostname==='127.0.0.1'){const form=new FormData();form.append('file',file);await api(`/api/sessions/${id}/files?replace=${replace}`,form)}else{const blob=await uploadBlob(`sessions/${id}/uploads/${file.name}`,file,{access:'private',handleUploadUrl:'/api/blob/upload',multipart:true});await api(`/api/sessions/${id}/blob-files?replace=${replace}`,{pathname:blob.pathname,filename:file.name,size:file.size})}setUploads(u=>u.map(x=>x.name===file.name?{...x,status:'Ready'}:x))}catch(e:any){setUploads(u=>u.map(x=>x.name===file.name?{...x,status:'Rejected',reason:e.message,file}:x));setError(e.message)}}await refresh(id);setFilters({});setTablePage(0)}catch(e:any){setError(e.message)}finally{setBusy('');if(input.current)input.current.value=''}}
async function remove(id?:string){if(busy)return;setBusy('Removing dataset…');generation.current++;queryCache.current.clear();setData(null);setError('');try{if(id){const m=await api(`/api/sessions/${sid}/files/${id}`,undefined,'DELETE');if(!m.rows)reset();else{setFilters({});setTablePage(0);await refresh(sid)}}else{await api(`/api/sessions/${sid}`,undefined,'DELETE');reset()}}catch(e:any){setError(e.message)}finally{setBusy('')}}
const toggle=useCallback((key:string,value:string)=>{setData(null);setFilters(f=>({...f,[key]:(f[key]||[]).includes(value)?f[key].filter(v=>v!==value):[...(f[key]||[]),value]}));setTablePage(0)},[]);
async function download(format:string){setError('');setBusy(`Preparing ${format.toUpperCase()}…`);try{const res=await fetch(format==='csv'?`/api/sessions/${sid}/export/csv`:'/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(format==='csv'?{filters,search,sort,descending}:{sid,filters,exclude_partial:exclude,buckets,pages:exportPages,format})});if(!res.ok){const err=await res.json();throw new Error(err.detail||err.error||'Export failed')}const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download=`Pharma_Sales_${meta?.options.year.join('-')||'data'}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setModal('')}catch(e:any){setError(e.message)}finally{setBusy('')}}
const filterCount=Object.values(filters).flat().length;
return <div className={'app '+(collapsed?'collapsed':'')}><aside className="sidebar"><a className="brand" href="/" aria-label="Pharma Sales Intelligence"><span className="brand-icon"><Activity size={23}/></span><span>pharma<span className="brand-light"> intelligence</span></span></a><button className="workspace-name" onClick={()=>setModal('files')}><span className="workspace-avatar">PI</span><span>Sales workspace<small>{loaded?'Dataset connected':'Your analytical workspace'}</small></span><ChevronRight size={14}/></button><nav aria-label="Dashboard navigation">{pages.map(([key,title],i)=>{const Icon=icons[i];return <button key={key} title={title} className={page===key?'active':''} onClick={()=>{if(key!==page)setData(null);setPage(key);setTablePage(0);setError('')}}><Icon size={18}/><span>{title==='Product intelligence'?'Products':title==='Customer intelligence'?'Customers':title==='Transaction explorer'?'Explorer':title}</span>{page===key&&<span className="nav-dot"/>}</button>})}</nav><div className="sidebar-bottom"><div className="session-note"><ShieldCheck size={18}/><span>Private by default<small>Session data clears after inactivity</small></span></div><button onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar"><PanelLeftClose size={18}/><span>Collapse sidebar</span></button></div></aside>
<div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>{current[1]}</strong></div><div className="header-actions">{loaded&&<><button className="quality-button" onClick={()=>setModal('quality')}><ShieldCheck size={16}/>{quality?.issues.length?`${quality.issues.length} audit notices`:'Audit passed'}</button><button onClick={()=>setModal('export')} disabled={!!busy}><Download size={16}/>Export</button><button title="Clear all data" aria-label="Clear all data" onClick={()=>remove()} disabled={!!busy}><Trash2 size={16}/></button></>}<span className="user-avatar">PI</span></div></header>
<main><input ref={input} type="file" multiple accept=".xlsx" hidden onChange={e=>upload(Array.from(e.target.files||[]))}/>{error&&<div role="alert" className="error"><Info size={17}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}{busy&&<div role="status" className="processing"><LoaderCircle className="spin" size={18}/>{busy}<span>Large workbooks may take a minute.</span></div>}
{!loaded?<div className="empty-workspace"><div className="empty-heading"><span className="empty-symbol"><Activity size={28}/></span><h1>Pharma Sales Intelligence</h1><p>Transform pharmaceutical sales workbooks into<br/>decision-ready intelligence.</p></div><div className={'dropzone '+(drag?'dragging':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(Array.from(e.dataTransfer.files))}}><span className="upload-icon"><Upload size={28}/></span><h2>Drop your pharmaceutical sales workbook here</h2><p>Bring your sales data. Find the story behind the numbers.</p><button className="button-primary" disabled={!!busy} onClick={()=>input.current?.click()}><Plus size={17}/>Browse workbooks</button><span className="upload-meta">XLSX files · Up to 100 MB each · Multiple files supported</span></div><div className="empty-footer"><span><Check size={15}/>Same-schema historical files can be combined</span><button onClick={async()=>{setSchema(await api('/api/schema'));setModal('schema')}}>View expected schema <ArrowUpRight size={14}/></button></div><div className="empty-explainer"><div><Database size={19}/><h3>One connected view</h3><p>Combine worksheets and years into one sales workspace.</p></div><div><ShieldCheck size={19}/><h3>Confidence in every number</h3><p>Review data quality before making decisions.</p></div><div><ChartNoAxesCombined size={19}/><h3>Built for your portfolio</h3><p>Explore brands, customers, pricing and shelf life.</p></div></div>{uploads.filter(u=>u.status==='Rejected').map(u=><div className="error" key={u.name}>{u.name}: {u.reason}{u.reason?.includes('already')&&<button onClick={()=>upload([u.file],true)}>Replace</button>}</div>)}</div>:<><div className="page-heading"><div><h1>{current[1]}</h1><p>{current[2]}</p></div><button className="dataset-label" onClick={()=>setModal('files')}><FileSpreadsheet size={17}/><span>{meta.files.length===1?meta.files[0].name:`${meta.files.length} workbooks`}<small>{meta.start} — {meta.end} · {fmt(meta.rows,'rows')} rows</small></span><ChevronRight size={16}/></button></div>
<div className="filterbar">{primary.slice(0,6).map(key=><details key={key} className="filter"><summary>{labels[key]}{filters[key]?.length?` (${filters[key].length})`:''}</summary><div className="filter-options">{(meta.options[key]||[]).map((v:string)=><label key={v}><input type="checkbox" checked={(filters[key]||[]).includes(v)} onChange={()=>toggle(key,v)}/>{v}</label>)}</div></details>)}<button className="more-filters" onClick={()=>setModal('filters')}><SlidersHorizontal size={15}/>All filters {filterCount>0&&<span>{filterCount}</span>}</button><button className="add-data" onClick={()=>input.current?.click()} disabled={!!busy}><Plus size={16}/>Add data</button></div>
{filterCount>0&&<div className="filter-chips">{Object.entries(filters).flatMap(([key,vs])=>vs.map(v=><button key={key+v} onClick={()=>toggle(key,v)}>{labels[key]||key}: {v}<X size={12}/></button>))}<button onClick={()=>{setFilters({});setTablePage(0)}}>Reset filters</button></div>}
{meta.partial&&<div className="partial-note"><Info size={15}/><span>Potential partial month: <strong>{meta.partial.period}</strong> · last invoice {meta.partial.last_date}</span>{page==='trends'&&<label><input type="checkbox" checked={exclude} onChange={e=>setExclude(e.target.checked)}/>Exclude from comparisons</label>}</div>}
{page==='trends'&&meta.options.fiscal_year.length>1&&<Comparison sid={sid} years={meta.options.fiscal_year} filters={filters} exclude={exclude}/>} 
{page==='geography'&&<label className="inline-control">Measure<select value={metric} onChange={e=>setMetric(e.target.value)}>{['net','quantity','invoices'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>}
{page==='pharma-risk'&&<div className="inline-control">Shelf-life bucket boundaries (days){buckets.map((v,i)=><input key={i} aria-label={`Shelf-life boundary ${i+1}`} type="number" min="1" value={v} onChange={e=>setBuckets(b=>b.map((n,j)=>i===j?Number(e.target.value):n))}/>)}<button onClick={()=>{setPage('explorer');setColumns(['batch','material','product','brand','mfg_date','expiry_date','date','shelf_days','quantity','net'])}}>Open batch explorer</button></div>}
{page==='explorer'&&(<div className="explorer-toolbar"><input aria-label="Search transactions" placeholder="Search invoice, customer, brand, batch…" value={search} onChange={e=>{setSearch(e.target.value);setTablePage(0)}}/><button onClick={()=>setModal('columns')}><SlidersHorizontal size={16}/>Columns</button><button onClick={()=>download('csv')}><Download size={16}/>Download CSV</button></div>)}
{loading||busy?<div className="loading-skeleton" aria-label="Loading analytics"><div/><div/><div/></div>:data&&(page==='explorer'?<><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}><button onClick={()=>{setSort(c);setDescending(sort===c?!descending:false)}}>{labels[c]||c}{sort===c?(descending?' ↓':' ↑'):''}</button></th>)}</tr></thead><tbody>{data.rows.map((r:Row,i:number)=><tr key={i} onClick={()=>setDetail(r)}>{columns.map(c=><td key={c}>{c==='invoice'?<button onClick={()=>setDetail(r)}>{r[c]}</button>:typeof r[c]==='number'?fmt(r[c],c):r[c]||'—'}</td>)}</tr>)}</tbody></table>{!data.rows.length&&<p className="chart-empty">No records match the current filters.</p>}</div><div className="pagination"><span>{fmt(data.total,'count')} matching rows · page {tablePage+1} of {Math.max(1,Math.ceil(data.total/50))}</span><button disabled={!tablePage} onClick={()=>setTablePage(p=>p-1)}>Previous</button><button disabled={(tablePage+1)*50>=data.total} onClick={()=>setTablePage(p=>p+1)}>Next</button></div></>:data.kpis.rows?<Dashboard page={page} data={data} onFilter={toggle} metric={metric}/>:<div className="chart-empty">No records match the current filters.<button onClick={()=>setFilters({})}>Reset filters</button></div>)}<footer className="dashboard-footer"><span>Pharma Sales Intelligence</span><span>INR · Based on invoice dates · Current filter context</span></footer></>}
</main></div>
{modal&&<Modal title={{quality:'Data quality audit',files:'Your dataset',filters:'Global filters',schema:'Expected workbook schema',export:'Export dashboard',columns:'Visible columns'}[modal]||modal} onClose={()=>setModal('')}>
{modal==='quality'&&quality&&<><p>{fmt(quality.processed,'rows')} rows processed · {quality.rejected} rejected · {fmt(quality.rows,'rows')} available</p><p className="notice">{quality.tolerance}</p>{quality.issues.length?quality.issues.map((issue:Row,i:number)=><details className="audit-item" key={i}><summary><span>{issue.kind}<small>{issue.field} {issue.file}</small></span><strong>{fmt(issue.count,'count')}</strong></summary><pre>{JSON.stringify(issue.examples,null,2)}</pre></details>):<p>All implemented checks passed.</p>}</>}
{modal==='files'&&<><button className="button-primary" onClick={()=>input.current?.click()} disabled={!!busy}><Plus size={16}/>Add workbooks</button>{(meta?.files||[]).map((f:Row)=><div className="file-item" key={f.id}><div><FileSpreadsheet size={22}/><strong>{f.name}</strong><button aria-label={`Remove ${f.name}`} disabled={!!busy} onClick={()=>remove(f.id)}><Trash2 size={16}/></button></div><p>{fmt(f.rows,'rows')} rows · {(f.size/1e6).toFixed(1)} MB · {f.sheets.filter((s:Row)=>s.status==='Imported').length} sheets imported · {f.issues.length?'Warning':'Ready'}</p><details><summary>Sheet validation</summary>{f.sheets.map((s:Row)=><p key={s.name}>{s.name} — {s.status}{s.reason?': '+s.reason:` · ${s.rows} rows`}</p>)}</details></div>)}{uploads.filter(u=>u.status==='Rejected').map(u=><div className="error" key={u.name}>{u.name}: {u.reason}{u.reason?.includes('already')&&<button onClick={()=>upload([u.file],true)}>Replace</button>}</div>)}{!loaded&&<p>No dataset loaded.</p>}{meta?.constants&&<details><summary>Constant fields</summary><p>{meta.constants.join(', ')}</p></details>}</>}
{modal==='filters'&&<><button onClick={()=>setFilters({})}>Reset filters</button><div className="all-filters">{Object.entries(meta?.options||{}).map(([key,values])=><fieldset key={key}><legend>{labels[key]||key}</legend><select aria-label={labels[key]||key} multiple value={filters[key]||[]} onChange={e=>{setFilters(f=>({...f,[key]:Array.from(e.target.selectedOptions).map(o=>o.value)}));setTablePage(0)}}>{(values as string[]).map(v=><option key={v}>{v}</option>)}</select></fieldset>)}</div><p>Hold Ctrl (Windows) or Command (Mac) to select multiple values.</p></>}
{modal==='schema'&&schema&&<><p>Every transaction sheet needs the required headings. Columns can be in any order. Summary sheets are skipped unless they match.</p>{['required','recommended','optional'].map(k=><section key={k}><h3>{k[0].toUpperCase()+k.slice(1)}</h3><p>{schema[k].join(' · ')}</p></section>)}<p>Dates: DD-MM-YYYY, ISO dates or Excel dates. Financial amounts may include thousands separators.</p></>}
{modal==='columns'&&<div className="column-options">{['date','invoice','customer','customer_name','customer_group','material','product','brand','therapy','plant','plant_name','district','city','ship_city','quantity','mrp','rate_before','rate_after','gross','discount','net','cgst','sgst','igst','utgst','batch','mfg_date','expiry_date','shelf_days','transporter','_source_file','_source_sheet','_source_row'].map(k=><label key={k}><input type="checkbox" checked={columns.includes(k)} onChange={()=>setColumns(c=>c.includes(k)?c.filter(v=>v!==k):[...c,k])}/>{labels[k]}</label>)}</div>}
{modal==='export'&&<><p>Export a fixed snapshot of your current filters. Pages keep the order shown below.</p><button onClick={()=>setExportPages(pages.slice(0,9).map(p=>p[0]))}>Select all</button><div className="export-options">{pages.slice(0,9).map(([key,title])=><label key={key}><input type="checkbox" checked={exportPages.includes(key)} onChange={()=>setExportPages(v=>v.includes(key)?v.filter(k=>k!==key):[...v,key])}/>{title}</label>)}</div><div className="export-actions"><button disabled={!!busy||!exportPages.length} onClick={()=>download('pdf')} className="button-primary"><Download size={16}/>Download PDF</button><button disabled={!!busy||!exportPages.length} onClick={()=>download('pptx')}><Download size={16}/>Download PowerPoint</button></div></>}
</Modal>}{detail&&<Modal title="Transaction details" onClose={()=>setDetail(null)}><dl className="row-details">{Object.entries(detail).map(([k,v])=><div key={k}><dt>{labels[k]||k}</dt><dd>{v==null?'Unavailable':String(v)}</dd></div>)}</dl></Modal>}</div>}





