import {NextRequest} from 'next/server';
import {chromium as playwright} from 'playwright-core';
import chromium from '@sparticuz/chromium';
import pptxgen from 'pptxgenjs';
import {readFile} from 'node:fs/promises';
import {pages,fmt,labels,Row} from '../../lib';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export const maxDuration=300;
const escape=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function POST(request:NextRequest){let browser;try{
const body=await request.json();if(!/^[a-f0-9]{64}$/.test(body.sid)||!['pdf','pptx'].includes(body.format)||!Array.isArray(body.pages)||!body.pages.length)return Response.json({error:'Invalid export request'},{status:400});
const selected=pages.slice(0,9).filter(p=>body.pages.includes(p[0]));if(!selected.length)return Response.json({error:'Select at least one page'},{status:400});
const response=await fetch(`${process.env.BACKEND_URL||'http://127.0.0.1:8000'}/api/sessions/${body.sid}/snapshot`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filters:body.filters||{},exclude_partial:!!body.exclude_partial,buckets:body.buckets||[180,365,548]})});if(!response.ok)return Response.json({error:(await response.json()).detail},{status:response.status});
const snap=await response.json();const script=await readFile(process.cwd()+'/node_modules/echarts/dist/echarts.min.js','utf8');
const font=await readFile(process.cwd()+'/node_modules/@fontsource/inter/files/inter-latin-400-normal.woff2');
const active=Object.entries(snap.filters).flatMap(([k,v])=>(v as string[]).map(x=>`${labels[k]||k}: ${x}`)).join(' · ')||'All data';
const charts:Row[]=[];
const sections=selected.map(([key,title],i)=>{const d=snap.pages[key];const definitions:Row[]=[];const add=(title:string,rows:Row[],metric='net',kind='bar')=>definitions.push({title,rows,metric,kind});
if(key==='trends'){add('Monthly net sales',d.trend,'net','line');add('Month-over-month growth',d.trend,'mom','column');add('Quantity trend',d.trend,'quantity','line');add('Weighted discount',d.trend,'discount_pct','line');}
else if(key==='pharma-risk'){add('Shelf-life revenue exposure',d.extra.shelf);add('Storage condition',d.groups.storage);add('Remaining shelf life',d.distributions.shelf_days,'quantity','column');add('Average shelf life by brand',d.extra.brand_shelf,'days');}
else if(key==='tax'){add('GST composition',Object.entries(d.extra.taxes).map(([name,net])=>({name,net})));add('Payment terms',d.groups.payment);add('GST by plant',d.groups.plant_name,'tax');add('Net sales by month',d.trend,'net','line');}
else {add('Net sales by month',d.trend,'net','line');for(const [dimension,rows] of Object.entries(d.groups).slice(0,3))add(labels[dimension]||dimension,rows as Row[],key==='commercial'?'discount':'net');}
return `<section class="sheet" id="page-${i}"><header><span>pharma intelligence</span><span>${escape(snap.metadata.start)} — ${escape(snap.metadata.end)}</span></header><h1>${escape(title)}</h1><p class="context">${escape(active)}</p><div class="metrics">${['net','gross','discount','quantity','invoices','discount_pct'].map(k=>`<div><label>${escape(labels[k])}</label><strong>${escape(fmt(d.kpis[k],k))}</strong></div>`).join('')}</div><div class="charts">${definitions.map(def=>{const id=charts.length;charts.push(def);return `<article><h2>${escape(def.title)}</h2><div id="chart-${id}" class="chart"></div></article>`}).join('')}</div><footer><span>${escape(snap.metadata.files.map((f:Row)=>f.name).join(' · '))}</span><span>${escape(snap.generated)} · ${i+1} / ${selected.length}</span></footer></section>`}).join('');
browser=await playwright.launch({headless:true,executablePath:process.env.VERCEL?await chromium.executablePath():undefined,args:process.env.VERCEL?chromium.args:[]});const page=await browser.newPage({viewport:{width:1600,height:900},deviceScaleFactor:2});
await page.setContent(`<!DOCTYPE html><html><head><style>@font-face{font-family:Inter;src:url(data:font/woff2;base64,${font.toString('base64')})}*{box-sizing:border-box}body{margin:0;font:14px Inter,sans-serif;color:#232933;background:#fff}.sheet{width:1600px;height:900px;padding:34px 48px;page-break-after:always;position:relative}.sheet:last-child{page-break-after:auto}header,footer{display:flex;justify-content:space-between;gap:20px;color:#6b7280;font-size:12px}header{padding-bottom:18px;border-bottom:1px solid #e5e8ec}header span:first-child{color:#bd591c;font-weight:bold;font-size:17px}h1{font-size:27px;margin:18px 0 7px}.context{font-size:11px;color:#6b7280;max-height:30px;overflow:hidden;margin:0 0 16px}.metrics{display:grid;grid-template-columns:repeat(6,1fr);padding:18px 0;border:1px solid #e5e8ec;border-radius:10px}.metrics>div{padding:0 20px;border-right:1px solid #e5e8ec}.metrics>div:last-child{border:0}label{font-size:12px;color:#6b7280}strong{display:block;font-size:25px;margin-top:8px}.metrics>div:first-child strong{color:#c95d18}.charts{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px}article{border:1px solid #e5e8ec;border-radius:10px;padding:15px;height:260px}h2{font-size:14px;margin:0 0 10px}.chart{height:210px;width:100%}footer{position:absolute;bottom:25px;left:48px;right:48px;font-size:10px}footer span:first-child{max-width:65%;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}@page{size:1600px 900px;margin:0}</style></head><body>${sections}</body></html>`);
await page.addScriptTag({content:script});
await page.evaluate((definitions)=>{definitions.forEach((d:any,i:number)=>{const chart=(window as any).echarts.init(document.getElementById('chart-'+i));const horizontal=d.kind==='bar';const rows=d.rows.filter((r:any)=>r.name!=null&&r[d.metric]!=null).slice(0,horizontal?8:40);if(horizontal)rows.reverse();chart.setOption({animation:false,color:['#e47128'],textStyle:{fontFamily:'Inter',fontSize:11,color:'#69727f'},grid:{top:8,bottom:25,left:horizontal?165:65,right:18},xAxis:{type:horizontal?'value':'category',data:horizontal?undefined:rows.map((r:any)=>r.name),axisTick:{show:false},axisLine:{show:false},axisLabel:{hideOverlap:true},splitLine:{show:horizontal,lineStyle:{color:'#edf0f2'}}},yAxis:{type:horizontal?'category':'value',data:horizontal?rows.map((r:any)=>r.name):undefined,axisLabel:{width:150,overflow:'truncate'},axisTick:{show:false},axisLine:{show:false},splitLine:{show:!horizontal,lineStyle:{color:'#edf0f2'}}},series:[{type:d.kind==='line'?'line':'bar',smooth:.2,barMaxWidth:20,data:rows.map((r:any)=>r[d.metric])}]});});return document.fonts.ready.then(()=>true)},charts);
let file:Buffer;let type:string;
if(body.format==='pdf'){file=await page.pdf({printBackground:true,preferCSSPageSize:true});type='application/pdf';}
else{const deck=new pptxgen();deck.layout='LAYOUT_WIDE';deck.author='Pharma Sales Intelligence';deck.subject='Filtered pharmaceutical sales snapshot';for(let i=0;i<selected.length;i++){const screenshot=await page.locator('#page-'+i).screenshot();const slide=deck.addSlide();slide.addImage({data:'image/png;base64,'+screenshot.toString('base64'),x:0,y:0,w:13.333333,h:7.5});}file=await deck.write({outputType:'nodebuffer'}) as Buffer;type='application/vnd.openxmlformats-officedocument.presentationml.presentation';}
return new Response(new Uint8Array(file),{headers:{'Content-Type':type,'Content-Disposition':`attachment; filename="Pharma_Sales_${snap.metadata.options.year.join('-')}.${body.format}"`,'Cache-Control':'no-store'}});
}catch(e:any){return Response.json({error:'Export could not finish: '+e.message},{status:500})}finally{await browser?.close()}}
